import os
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import accuracy_score, r2_score
import numpy as np

try:
    from micromlgen import port
except ImportError:
    port = None

try:
    import m2cgen as m2c
except ImportError:
    m2c = None

df = pd.read_csv("synthetic_ev_data.csv")

features = [
    "hourOfDay",
    "dayOfWeek",
    "bayOccupied",
    "recentAvgCurrent",
    "sessionElapsedMin",
]

X_arrival = df[features]
y_arrival = df["arrivedWithinWindow"]

occupied = df["bayOccupied"] == 1
X_duration = df.loc[occupied, features]
y_duration = df.loc[occupied, "actualDurationMin"]

arrival_model = LogisticRegression(max_iter=500).fit(X_arrival, y_arrival)
duration_model = DecisionTreeRegressor(max_depth=5, random_state=42).fit(
    X_duration, y_duration
)

arrival_pred = arrival_model.predict(X_arrival)
duration_pred = duration_model.predict(X_duration)

print("Arrival accuracy:", accuracy_score(y_arrival, arrival_pred))
print("Duration R2:", r2_score(y_duration, duration_pred))

# Optional real export if micromlgen/m2cgen are installed.
if port is not None and m2c is not None:
    arrival_c = m2c.export_to_c(arrival_model)
    duration_c = port(duration_model)
    with open("../firmware/model.h", "w", encoding="utf-8") as f:
        f.write("// Generated by train_models.py\n")
        f.write("#pragma once\n")
        f.write(arrival_c)
        f.write("\n")
        f.write(duration_c)
    print("Exported trained C/C++ model to ../firmware/model.h")
else:
    print("micromlgen/m2cgen not installed.")
    print("Keeping the included starter model.h so the Wokwi firmware remains runnable.")
